alias cman='man -Hlinks2'
alias melkki='ssh melkki.cs.helsinki.fi'
alias melkinpaasi='ssh melkinpaasi.cs.helsinki.fi'
alias melkinkari='ssh melkinkari.cs.helsinki.fi'
alias melkinphysics='ssh login.physics.helsinki.fi'
